[build-system]
requires = [
    "setuptools>=61",
    "wheel",
    "torch"
]
build-backend = "setuptools.build_meta"

[project]
name = "istr"
version = "1.0.0"
description = "ISTR: End-to-End Instance Segmentation with Transformers"
requires-python = ">=3.8"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [ { name = "ISTR Authors" } ]
dependencies = [
    "torch>=1.8",
    "torchvision",
    "opencv-python",
    "scipy",
    "shapely",
    "torch_dct",
    "timm",
]
optional-dependencies = { dev = ["black==22.3.0", "flake8", "isort"] }

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
"" = "projects/ISTR"

[tool.setuptools.packages.find]
where = ["projects/ISTR"]
include = ["istr", "istr.*"]